using SchoolManagement.DAL.Repositories.Interfaces;

namespace SchoolManagement.DAL.UnitOfWork;

public interface IUnitOfWork : IAsyncDisposable
{
    ITenantRepository Tenants { get; }
    ISchoolRepository Schools { get; }
    IUserRepository Users { get; }
    IStudentRepository Students { get; }
    IGuardianRepository Guardians { get; }
    IAdmissionLookupRepository AdmissionLookups { get; }
    IOnlineAdmissionRepository OnlineAdmissions { get; }
    IImportRepository Imports { get; }
    IStudentCategoryRepository StudentCategories { get; }
    IDeactivateReasonRepository DeactivateReasons { get; }
    IDepartmentRepository Departments { get; }
    IDesignationRepository Designations { get; }
    IEmployeeRepository Employees { get; }
    ISalaryTemplateRepository SalaryTemplates { get; }
    ISalaryAssignmentRepository SalaryAssignments { get; }
    ISalaryPaymentRepository SalaryPayments { get; }
    IAdvanceSalaryRepository AdvanceSalaries { get; }
    ILeaveCategoryRepository LeaveCategories { get; }
    ILeaveRequestRepository LeaveRequests { get; }
    IAwardRepository Awards { get; }
    IClassControlRepository ClassControls { get; }
    ISectionControlRepository SectionControls { get; }
    IClassTeacherRepository ClassTeachers { get; }
    ISubjectRepository Subjects { get; }
    IClassSubjectAssignmentRepository ClassSubjectAssignments { get; }
    IClassScheduleRepository ClassSchedules { get; }
    IStudentPromotionRepository StudentPromotions { get; }
    IExamTermRepository ExamTerms { get; }
    IExamHallRepository ExamHalls { get; }
    IMarkDistributionRepository MarkDistributions { get; }
    IExamRepository Exams { get; }
    IExamScheduleRepository ExamSchedules { get; }
    IMarkEntryRepository MarkEntries { get; }
    IGradeRangeRepository GradeRanges { get; }
    IExamPositionRepository ExamPositions { get; }
    IStudentAttendanceRepository StudentAttendances { get; }
    IEmployeeAttendanceRepository EmployeeAttendances { get; }
    IExamAttendanceRepository ExamAttendances { get; }
    IBookCategoryRepository BookCategories { get; }
    IBookRepository Books { get; }
    IBookIssueRepository BookIssues { get; }
    IEventTypeRepository EventTypes { get; }
    IEventRepository Events { get; }
    IFeesTypeRepository FeesTypes { get; }
    IFeesGroupRepository FeesGroups { get; }
    IFeesGroupItemRepository FeesGroupItems { get; }
    IFeesAllocationRepository FeesAllocations { get; }
    IFineSetupRepository FineSetups { get; }
    IFeesReminderRepository FeesReminders { get; }
    IStudentFeeInvoiceRepository StudentFeeInvoices { get; }
    IOfflinePaymentRepository OfflinePayments { get; }
    IOfflinePaymentTypeRepository OfflinePaymentTypes { get; }
    IAccountingAccountRepository AccountingAccounts { get; }
    IAccountingDepositRepository AccountingDeposits { get; }
    IAccountingExpenseRepository AccountingExpenses { get; }
    IVoucherHeadRepository VoucherHeads { get; }
    IMessageRepository Messages { get; }
    ISchoolSettingsRepository SchoolSettings { get; }
    IGlobalSettingsRepository GlobalSettings { get; }
    IBiometricDeviceRepository BiometricDevices { get; }
    IBiometricUserMapRepository BiometricUserMaps { get; }
    IBiometricPunchLogRepository BiometricPunchLogs { get; }
    IBiometricDeviceRegistryRepository BiometricDeviceRegistries { get; }
    IRoleRepository Roles { get; }
    IAcademicSessionRepository AcademicSessions { get; }
    IDatabaseBackupRepository DatabaseBackups { get; }
    ILoginLogRepository LoginLogs { get; }
    IEmailSettingsRepository EmailSettings { get; }
    ISmsSettingsRepository SmsSettings { get; }
    ICronSecretRegistryRepository CronSecretRegistries { get; }
    Task BeginTenantTransactionAsync(CancellationToken cancellationToken = default);
    Task CommitTenantTransactionAsync(CancellationToken cancellationToken = default);
    Task RollbackTenantTransactionAsync(CancellationToken cancellationToken = default);
    void ClearTenantChangeTracker();
    Task<int> SaveMasterChangesAsync(CancellationToken cancellationToken = default);
    Task<int> SaveTenantChangesAsync(CancellationToken cancellationToken = default);
}
